name: Keep Backend Awake

on:
  schedule:
    - cron: "*/9 * * * *"  # Runs every 9 minutes

  workflow_dispatch:  # Allows manual trigger

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run keep_alive.py
        run: python keep_alive.py
